default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: ferris

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
